# Site
title:              ACM Chicago
bio:                'ACM Student Chapter @ LUC.'
description:        "Splash page for student Chapter."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/acm_chapter.gif'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://taylantatli.github.io/Moon

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              contact@relativiti.io
twitter:            relativitiACM
facebook:           Relativiti-363318634052637
github-url:         RelativitiACM
#stackoverflow:     123456/username
#linkedin:          username
#xing:              username
instagram:          relativitiACM
#lastfm:            username
tumblr:            relativitiACM
medium:            '@relativitiACM'
#pinterest:         username
#foursquare:        username
steam:              Relativiti
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#twitch:            username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
